# Generated by Django 5.2.1 on 2025-06-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/'),
        ),
    ]
